name: beautiful_counter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  device_preview: ^1.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  google_fonts: ^4.0.4
  hydrated_bloc: ^9.1.1
  mocktail: ^0.3.0
  path_provider: ^2.0.15
  rive: ^0.11.2
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/

fonts:
    - family: MonomaniacOne
      fonts:
        - assets/fonts/MonomaniacOne-Regular.ttf
    - family: Pixel
      fonts:
        - assets/fonts/PixelRegular.ttf
      